import Foundation

enum BrushColorTag: String, Codable, Sendable, CaseIterable {
    case red
    case orange
    case yellow
    case green
    case cyan
    case blue
    case purple
}

struct BrushPreset: Codable, Sendable, Equatable, Identifiable {
    let id: String
    var name: String
    var brush: BrushSettings
    var isBuiltIn: Bool
    var slotIndex: Int? = nil
    var colorTag: BrushColorTag? = nil
    var isFavorite: Bool = false

    private enum CodingKeys: String, CodingKey {
        case id
        case name
        case brush
        case isBuiltIn
        case slotIndex
        case colorTag
        case isFavorite
    }

    init(
        id: String,
        name: String,
        brush: BrushSettings,
        isBuiltIn: Bool,
        slotIndex: Int? = nil,
        colorTag: BrushColorTag? = nil,
        isFavorite: Bool = false
    ) {
        self.id = id
        self.name = name
        self.brush = brush
        self.isBuiltIn = isBuiltIn
        self.slotIndex = slotIndex
        self.colorTag = colorTag
        self.isFavorite = isFavorite
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(String.self, forKey: .id)
        name = try container.decode(String.self, forKey: .name)
        brush = try container.decode(BrushSettings.self, forKey: .brush)
        isBuiltIn = try container.decode(Bool.self, forKey: .isBuiltIn)
        slotIndex = try container.decodeIfPresent(Int.self, forKey: .slotIndex)
        colorTag = try container.decodeIfPresent(BrushColorTag.self, forKey: .colorTag)
        isFavorite = try container.decodeIfPresent(Bool.self, forKey: .isFavorite) ?? false
    }
}

enum BrushPresetSaveDisposition: Sendable, Equatable {
    case created
    case replaced
    case selectedExisting
}

struct BrushPresetSaveResult: Sendable, Equatable {
    var preset: BrushPreset
    var disposition: BrushPresetSaveDisposition
}

extension BrushPreset {
    static let pressureGrainCrayonPresetID = "builtin-pressure-grain-crayon"
    static let pressureGrainCrayonSourceTipAssetID = BrushTipImageAssetID(
        rawValue: "tip-11cb1eef9c21104dbe40e15664a2b0c2792b4df7dd81cb94a813a8dc68c34bea"
    )

    static let retiredBrushDemoPresetIDs: Set<String> = [
        "builtin-dual-tip-tighten",
        "builtin-dual-tip-soft-compress",
        "builtin-dual-tip-strong-modulate"
    ]

    var isRetiredBrushDemoPreset: Bool {
        Self.retiredBrushDemoPresetIDs.contains(id)
    }

    var usesAutoGeneratedName: Bool {
        let prefix = "笔刷 "
        guard name.hasPrefix(prefix) else { return false }
        let suffix = name.dropFirst(prefix.count)
        guard let number = Int(suffix), number > 0 else { return false }
        return true
    }

    var isLikelyAutoSavedDuplicateCandidate: Bool {
        !isBuiltIn && colorTag == nil && usesAutoGeneratedName
    }

    static func pressureGrainCrayon(
        derivedFrom source: BrushPreset,
        slotIndex: Int
    ) -> BrushPreset? {
        guard
            source.brush.customTipAssetID == pressureGrainCrayonSourceTipAssetID,
            source.brush.customTipEnvelopeMaskData?.isEmpty == false,
            source.brush.compoundBrush.secondary.customTipMaskData?.isEmpty == false
        else {
            return nil
        }

        var brush = source.brush
        // Exact working size and transfer model from Krita preset 06-01-蜡笔.
        brush.size = 126
        brush.opacity = 1
        // Krita PaintOpAction=2 is WASH: repeated dabs in one stroke share an
        // opacity ceiling instead of accumulating like BUILDUP.
        brush.buildMode = .opacityCap
        brush.spacingPercent = 6
        brush.scatterAmount = 0
        brush.jitterAmount = 0
        brush.colorJitterAmount = 0
        brush.paintJitterAmount = 0
        brush.paintContrastAmount = 0
        brush.stampRotationDegrees = 0
        brush.followsStrokeDirection = true
        // The imported grayscale mask should pass through with an exponent of
        // approximately one. ArtFlex's softness mapping reaches that at 44/49.
        brush.customTipSoftness = 44.0 / 49.0
        brush.customTipRoundness = 1
        brush.customTipAngleDegrees = 0
        brush.pressureSensitivity = 1
        brush.sizeLowerBound = 0
        brush.pressureSizeAmount = 1
        brush.setSizePressureCurveState(
            CurveChannelState(points: [
                .init(x: 0, y: 0.389558),
                .init(x: 0.305221, y: 0.658635),
                .init(x: 1, y: 1)
            ])
        )
        brush.pressureOpacityAmount = 1
        brush.buildUpOpacityCompensationAmount = 0
        brush.setOpacityPressureCurveState(
            CurveChannelState(points: [
                .init(x: 0, y: 0),
                .init(x: 1, y: 1)
            ])
        )

        brush.compoundBrush.enabled = true
        brush.compoundBrush.mode = .maskedOverlay
        brush.compoundBrush.pressureMix = .balanced
        brush.compoundBrush.globalPressureSizeAmount = 0
        brush.compoundBrush.globalPressureOpacityAmount = 0
        brush.compoundBrush.globalPaintJitterAmount = 0
        brush.compoundBrush.globalPaintContrastAmount = 0

        brush.compoundBrush.secondary.followsStrokeDirection = false
        brush.compoundBrush.secondary.sizeMode = .relativeToPrimary
        // Krita MaskingBrush/MasterSizeCoeff and the embedded B-tip spacing.
        brush.compoundBrush.secondary.relativeSizeRatio = 1.5454545454545454
        brush.compoundBrush.secondary.spacingPercent = 75
        brush.compoundBrush.secondary.softness = 44.0 / 49.0
        brush.compoundBrush.secondary.pressureSizeAmount = 1
        brush.compoundBrush.secondary.sizeCurveLow = 0.2
        brush.compoundBrush.secondary.sizeCurveMid = 0.5
        brush.compoundBrush.secondary.sizeCurveHigh = 0.8
        brush.compoundBrush.secondary.pressureOpacityAmount = 1
        brush.compoundBrush.secondary.opacityPressureCurve = CurveChannelState(points: [
            .init(x: 0, y: 0.492462),
            .init(x: 0.253695, y: 1),
            .init(x: 1, y: 1)
        ])
        brush.compoundBrush.secondary.opacityCurveLow = 0.85
        brush.compoundBrush.secondary.opacityCurveMid = 1
        brush.compoundBrush.secondary.opacityCurveHigh = 1
        brush.compoundBrush.secondary.tileRandomRotation = 1
        brush.compoundBrush.secondary.pressureRotationAmount = 1

        return BrushPreset(
            id: pressureGrainCrayonPresetID,
            name: "颗粒蜡笔",
            brush: brush,
            isBuiltIn: true,
            slotIndex: slotIndex,
            colorTag: .cyan
        )
    }
}

struct BrushLibraryState: Codable, Sendable, Equatable {
    var presets: [BrushPreset]
    var selectedPresetID: String?
    var recentPresetIDs: [String]
    var deletedPresets: [BrushPreset]

    static let stageOneDefault = BrushLibraryState(
        presets: [],
        selectedPresetID: nil,
        recentPresetIDs: [],
        deletedPresets: []
    )

    enum CodingKeys: String, CodingKey {
        case presets
        case selectedPresetID
        case recentPresetIDs
        case deletedPresets
    }

    init(
        presets: [BrushPreset],
        selectedPresetID: String?,
        recentPresetIDs: [String] = [],
        deletedPresets: [BrushPreset] = []
    ) {
        self.presets = presets
        self.selectedPresetID = selectedPresetID
        self.recentPresetIDs = []
        self.deletedPresets = deletedPresets
        self.recentPresetIDs = sanitizedRecentPresetIDs(recentPresetIDs)
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let presets = try container.decode([BrushPreset].self, forKey: .presets)
        let selectedPresetID = try container.decodeIfPresent(String.self, forKey: .selectedPresetID)
        let recentPresetIDs = try container.decodeIfPresent([String].self, forKey: .recentPresetIDs) ?? []
        let deletedPresets = try container.decodeIfPresent([BrushPreset].self, forKey: .deletedPresets) ?? []

        self.init(
            presets: presets,
            selectedPresetID: selectedPresetID,
            recentPresetIDs: recentPresetIDs,
            deletedPresets: deletedPresets
        )
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(presets, forKey: .presets)
        try container.encode(selectedPresetID, forKey: .selectedPresetID)
        try container.encode(recentPresetIDs, forKey: .recentPresetIDs)
        try container.encode(deletedPresets, forKey: .deletedPresets)
    }

    func preset(id: String) -> BrushPreset? {
        presets.first(where: { $0.id == id })
    }

    mutating func selectPreset(id: String?) {
        selectedPresetID = id
    }

    mutating func notePresetUsed(_ id: String) {
        guard isEligibleForRecentPresetUsage(id) else { return }
        recentPresetIDs.removeAll { $0 == id }
        recentPresetIDs.insert(id, at: 0)
        if recentPresetIDs.count > 4 {
            recentPresetIDs = Array(recentPresetIDs.prefix(4))
        }
    }

    func recentPresets(limit: Int = 4) -> [BrushPreset] {
        let limitedIDs = recentPresetIDs.prefix(limit)
        return limitedIDs.compactMap { preset(id: $0) }
    }

    func launchDefaultPreset() -> BrushPreset? {
        preset(atSlot: 0) ?? presets.first
    }

    func resolvedSlotIndex(forPresetID id: String) -> Int? {
        resolvedSlotMap()[id]
    }

    func isEligibleForRecentPresetUsage(_ id: String) -> Bool {
        guard preset(id: id) != nil,
              let slotIndex = resolvedSlotIndex(forPresetID: id) else {
            return false
        }
        return slotIndex >= 4
    }

    mutating func saveCurrentPreset(brush: BrushSettings) -> BrushPreset {
        if let existing = presets.first(where: { !$0.isBuiltIn && $0.brush == brush }) {
            selectedPresetID = existing.id
            return existing
        }

        let nextCustomIndex = presets.filter { !$0.isBuiltIn }.count + 1
        let nextSlot = firstEmptySlotIndex()
        let preset = BrushPreset(
            id: UUID().uuidString,
            name: "笔刷 \(nextCustomIndex)",
            brush: brush,
            isBuiltIn: false,
            slotIndex: nextSlot
        )
        presets.append(preset)
        selectedPresetID = preset.id
        return preset
    }

    mutating func saveNamedPreset(
        brush: BrushSettings,
        name: String,
        colorTag: BrushColorTag?,
        replacingPresetID: String? = nil,
        allowsDuplicate: Bool = false
    ) -> BrushPresetSaveResult {
        let trimmedName = name.trimmingCharacters(in: .whitespacesAndNewlines)

        if let replacingPresetID,
           let index = presets.firstIndex(where: { $0.id == replacingPresetID && !$0.isBuiltIn }) {
            presets[index].name = trimmedName.isEmpty ? presets[index].name : trimmedName
            presets[index].brush = brush
            presets[index].colorTag = colorTag
            selectedPresetID = replacingPresetID
            return BrushPresetSaveResult(preset: presets[index], disposition: .replaced)
        }

        if allowsDuplicate == false,
           let existing = presets.first(where: { !$0.isBuiltIn && $0.brush == brush }) {
            selectedPresetID = existing.id
            return BrushPresetSaveResult(preset: existing, disposition: .selectedExisting)
        }

        let nextCustomIndex = presets.filter { !$0.isBuiltIn }.count + 1
        let preset = BrushPreset(
            id: UUID().uuidString,
            name: trimmedName.isEmpty ? "笔刷 \(nextCustomIndex)" : trimmedName,
            brush: brush,
            isBuiltIn: false,
            slotIndex: firstEmptySlotIndex(),
            colorTag: colorTag
        )
        presets.append(preset)
        selectedPresetID = preset.id
        return BrushPresetSaveResult(preset: preset, disposition: .created)
    }

    mutating func deletePreset(id: String) -> Bool {
        guard let index = presets.firstIndex(where: { $0.id == id && !$0.isBuiltIn }) else {
            return false
        }

        deletedPresets.append(presets.remove(at: index))
        if deletedPresets.count > 12 {
            deletedPresets.removeFirst(deletedPresets.count - 12)
        }
        recentPresetIDs.removeAll { $0 == id }
        if selectedPresetID == id {
            selectedPresetID = presets.first?.id
        }
        return true
    }

    mutating func restoreMostRecentlyDeletedPreset() -> BrushPreset? {
        guard var restoredPreset = deletedPresets.popLast() else { return nil }
        if let slotIndex = restoredPreset.slotIndex, preset(atSlot: slotIndex) != nil {
            restoredPreset.slotIndex = firstEmptySlotIndex()
        }
        presets.append(restoredPreset)
        selectedPresetID = restoredPreset.id
        return restoredPreset
    }

    mutating func renamePreset(id: String, to name: String) -> Bool {
        let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty,
              let index = presets.firstIndex(where: { $0.id == id && !$0.isBuiltIn }) else {
            return false
        }
        presets[index].name = trimmed
        return true
    }

    mutating func setFavorite(_ isFavorite: Bool, forPresetID id: String) {
        guard let index = presets.firstIndex(where: { $0.id == id }) else { return }
        presets[index].isFavorite = isFavorite
    }

    mutating func duplicatePreset(id: String) -> BrushPreset? {
        guard var duplicate = preset(id: id) else { return nil }
        duplicate = BrushPreset(
            id: UUID().uuidString,
            name: "\(duplicate.name) 副本",
            brush: duplicate.brush,
            isBuiltIn: false,
            slotIndex: firstEmptySlotIndex(),
            colorTag: duplicate.colorTag,
            isFavorite: false
        )
        presets.append(duplicate)
        selectedPresetID = duplicate.id
        return duplicate
    }

    func resolvedSlotMap() -> [String: Int] {
        var assignments: [String: Int] = [:]
        var occupied = Set<Int>()

        for preset in presets {
            guard let slotIndex = preset.slotIndex, slotIndex >= 0, !occupied.contains(slotIndex) else {
                continue
            }
            assignments[preset.id] = slotIndex
            occupied.insert(slotIndex)
        }

        var nextFreeSlot = 0
        for preset in presets where assignments[preset.id] == nil {
            while occupied.contains(nextFreeSlot) {
                nextFreeSlot += 1
            }
            assignments[preset.id] = nextFreeSlot
            occupied.insert(nextFreeSlot)
        }

        return assignments
    }

    func firstEmptySlotIndex() -> Int {
        let occupied = Set(resolvedSlotMap().values)
        var candidate = 0
        while occupied.contains(candidate) {
            candidate += 1
        }
        return candidate
    }

    func preset(atSlot slotIndex: Int) -> BrushPreset? {
        let slotMap = resolvedSlotMap()
        return presets.first { slotMap[$0.id] == slotIndex }
    }

    mutating func setColorTag(_ tag: BrushColorTag?, forPresetID id: String) {
        guard let index = presets.firstIndex(where: { $0.id == id }) else { return }
        presets[index].colorTag = tag
    }

    mutating func movePreset(id: String, toSlot targetSlotIndex: Int) -> Bool {
        guard targetSlotIndex >= 0,
              let sourceIndex = presets.firstIndex(where: { $0.id == id }) else {
            return false
        }

        let slotMap = resolvedSlotMap()
        let sourceSlotIndex = slotMap[id] ?? targetSlotIndex
        let targetPresetID = slotMap.first { $0.value == targetSlotIndex }?.key

        presets[sourceIndex].slotIndex = targetSlotIndex

        if let targetPresetID, targetPresetID != id,
           let targetIndex = presets.firstIndex(where: { $0.id == targetPresetID }) {
            presets[targetIndex].slotIndex = sourceSlotIndex
        }

        recentPresetIDs = sanitizedRecentPresetIDs(recentPresetIDs)

        return true
    }

    func removingRetiredBrushDemoPresets() -> BrushLibraryState {
        let filteredPresets = presets.filter { !$0.isRetiredBrushDemoPreset }
        let resolvedSelectedPresetID: String?

        if let selectedPresetID,
           filteredPresets.contains(where: { $0.id == selectedPresetID }) {
            resolvedSelectedPresetID = selectedPresetID
        } else {
            resolvedSelectedPresetID = filteredPresets.first?.id
        }

        return BrushLibraryState(
            presets: filteredPresets,
            selectedPresetID: resolvedSelectedPresetID,
            recentPresetIDs: recentPresetIDs,
            deletedPresets: deletedPresets
        )
    }

    func removingLikelyAutoSavedDuplicatePresets() -> BrushLibraryState {
        var filteredPresets: [BrushPreset] = []
        var resolvedSelectedPresetID = selectedPresetID

        for preset in presets {
            if preset.isLikelyAutoSavedDuplicateCandidate,
               let existing = filteredPresets.first(where: {
                   $0.isLikelyAutoSavedDuplicateCandidate && $0.brush == preset.brush
               }) {
                if resolvedSelectedPresetID == preset.id {
                    resolvedSelectedPresetID = existing.id
                }
                continue
            }
            filteredPresets.append(preset)
        }

        if let selectedPresetID = resolvedSelectedPresetID,
           filteredPresets.contains(where: { $0.id == selectedPresetID }) == false {
            resolvedSelectedPresetID = filteredPresets.first?.id
        }

        return BrushLibraryState(
            presets: filteredPresets,
            selectedPresetID: resolvedSelectedPresetID,
            recentPresetIDs: recentPresetIDs,
            deletedPresets: deletedPresets
        )
    }

    func installingOrUpdatingPressureGrainCrayonPresetIfPossible() -> BrushLibraryState {
        guard let source = preset(atSlot: 3),
              let crayon = BrushPreset.pressureGrainCrayon(
                derivedFrom: source,
                slotIndex: preset(id: BrushPreset.pressureGrainCrayonPresetID)?.slotIndex
                    ?? firstEmptySlotIndex()
              ) else {
            return self
        }

        var installed = self
        if let existingIndex = installed.presets.firstIndex(where: {
            $0.id == BrushPreset.pressureGrainCrayonPresetID
        }) {
            installed.presets[existingIndex] = crayon
        } else {
            installed.presets.append(crayon)
        }
        return installed
    }

    private func sanitizedRecentPresetIDs(_ ids: [String]) -> [String] {
        var seen = Set<String>()
        var sanitized: [String] = []

        for id in ids where isEligibleForRecentPresetUsage(id) && seen.insert(id).inserted {
            sanitized.append(id)
            if sanitized.count == 4 {
                break
            }
        }

        return sanitized
    }
}

struct BrushLibraryArchive: Codable, Sendable, Equatable {
    var version: Int = 3
    var library: BrushLibraryState
    var tipImageLibrary: TipImageLibraryState
    var tipImageAssets: [BrushTipImageAsset]

    init(
        version: Int = 3,
        library: BrushLibraryState,
        tipImageLibrary: TipImageLibraryState = .empty,
        tipImageAssets: [BrushTipImageAsset]? = nil
    ) {
        self.version = version
        if let tipImageAssets {
            self.library = library
            self.tipImageLibrary = tipImageLibrary
            self.tipImageAssets = tipImageAssets
        } else {
            let normalized = BrushTipImageAssetSystem.archivedLibrary(
                library,
                tipImageLibrary: tipImageLibrary
            )
            self.library = normalized.library
            self.tipImageLibrary = normalized.tipImageLibrary
            self.tipImageAssets = normalized.assets
        }
    }

    enum CodingKeys: String, CodingKey {
        case version
        case library
        case tipImageLibrary
        case tipImageAssets
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        version = try container.decodeIfPresent(Int.self, forKey: .version) ?? 1
        library = try container.decode(BrushLibraryState.self, forKey: .library)
        tipImageLibrary = try container.decodeIfPresent(TipImageLibraryState.self, forKey: .tipImageLibrary) ?? .empty
        tipImageAssets = try container.decodeIfPresent([BrushTipImageAsset].self, forKey: .tipImageAssets) ?? []
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(version, forKey: .version)
        try container.encode(library, forKey: .library)
        try container.encode(tipImageLibrary, forKey: .tipImageLibrary)
        try container.encode(tipImageAssets, forKey: .tipImageAssets)
    }

    var resolvedLibrary: BrushLibraryState {
        BrushTipImageAssetSystem.resolveLibrary(library, assets: tipImageAssets)
    }

    var resolvedTipImageLibrary: TipImageLibraryState {
        BrushTipImageAssetSystem.resolveTipImageLibrary(tipImageLibrary, assets: tipImageAssets)
    }
}
