import Foundation

enum BrushColorTag: String, Codable, Sendable, CaseIterable {
    case red
    case orange
    case yellow
    case green
    case cyan
    case blue
    case purple
}

struct BrushPreset: Codable, Sendable, Equatable, Identifiable {
    let id: String
    var name: String
    var brush: BrushSettings
    var isBuiltIn: Bool
    var slotIndex: Int? = nil
    var colorTag: BrushColorTag? = nil
}

extension BrushPreset {
    static let retiredBrushDemoPresetIDs: Set<String> = [
        "builtin-dual-tip-tighten",
        "builtin-dual-tip-soft-compress",
        "builtin-dual-tip-strong-modulate"
    ]

    var isRetiredBrushDemoPreset: Bool {
        Self.retiredBrushDemoPresetIDs.contains(id)
    }

    var usesAutoGeneratedName: Bool {
        let prefix = "笔刷 "
        guard name.hasPrefix(prefix) else { return false }
        let suffix = name.dropFirst(prefix.count)
        guard let number = Int(suffix), number > 0 else { return false }
        return true
    }

    var isLikelyAutoSavedDuplicateCandidate: Bool {
        !isBuiltIn && colorTag == nil && usesAutoGeneratedName
    }
}

struct BrushLibraryState: Codable, Sendable, Equatable {
    var presets: [BrushPreset]
    var selectedPresetID: String?

    static let stageOneDefault = BrushLibraryState(
        presets: [],
        selectedPresetID: nil
    )

    func preset(id: String) -> BrushPreset? {
        presets.first(where: { $0.id == id })
    }

    mutating func selectPreset(id: String?) {
        selectedPresetID = id
    }

    mutating func saveCurrentPreset(brush: BrushSettings) -> BrushPreset {
        if let existing = presets.first(where: { !$0.isBuiltIn && $0.brush == brush }) {
            selectedPresetID = existing.id
            return existing
        }

        let nextCustomIndex = presets.filter { !$0.isBuiltIn }.count + 1
        let nextSlot = firstEmptySlotIndex()
        let preset = BrushPreset(
            id: UUID().uuidString,
            name: "笔刷 \(nextCustomIndex)",
            brush: brush,
            isBuiltIn: false,
            slotIndex: nextSlot
        )
        presets.append(preset)
        selectedPresetID = preset.id
        return preset
    }

    mutating func deletePreset(id: String) -> Bool {
        guard let index = presets.firstIndex(where: { $0.id == id }) else {
            return false
        }

        presets.remove(at: index)
        if selectedPresetID == id {
            selectedPresetID = presets.first?.id
        }
        return true
    }

    func resolvedSlotMap() -> [String: Int] {
        var assignments: [String: Int] = [:]
        var occupied = Set<Int>()

        for preset in presets {
            guard let slotIndex = preset.slotIndex, slotIndex >= 0, !occupied.contains(slotIndex) else {
                continue
            }
            assignments[preset.id] = slotIndex
            occupied.insert(slotIndex)
        }

        var nextFreeSlot = 0
        for preset in presets where assignments[preset.id] == nil {
            while occupied.contains(nextFreeSlot) {
                nextFreeSlot += 1
            }
            assignments[preset.id] = nextFreeSlot
            occupied.insert(nextFreeSlot)
        }

        return assignments
    }

    func firstEmptySlotIndex() -> Int {
        let occupied = Set(resolvedSlotMap().values)
        var candidate = 0
        while occupied.contains(candidate) {
            candidate += 1
        }
        return candidate
    }

    func preset(atSlot slotIndex: Int) -> BrushPreset? {
        let slotMap = resolvedSlotMap()
        return presets.first { slotMap[$0.id] == slotIndex }
    }

    mutating func setColorTag(_ tag: BrushColorTag?, forPresetID id: String) {
        guard let index = presets.firstIndex(where: { $0.id == id }) else { return }
        presets[index].colorTag = tag
    }

    mutating func movePreset(id: String, toSlot targetSlotIndex: Int) -> Bool {
        guard targetSlotIndex >= 0,
              let sourceIndex = presets.firstIndex(where: { $0.id == id }) else {
            return false
        }

        let slotMap = resolvedSlotMap()
        let sourceSlotIndex = slotMap[id] ?? targetSlotIndex
        let targetPresetID = slotMap.first { $0.value == targetSlotIndex }?.key

        presets[sourceIndex].slotIndex = targetSlotIndex

        if let targetPresetID, targetPresetID != id,
           let targetIndex = presets.firstIndex(where: { $0.id == targetPresetID }) {
            presets[targetIndex].slotIndex = sourceSlotIndex
        }

        return true
    }

    func removingRetiredBrushDemoPresets() -> BrushLibraryState {
        let filteredPresets = presets.filter { !$0.isRetiredBrushDemoPreset }
        let resolvedSelectedPresetID: String?

        if let selectedPresetID,
           filteredPresets.contains(where: { $0.id == selectedPresetID }) {
            resolvedSelectedPresetID = selectedPresetID
        } else {
            resolvedSelectedPresetID = filteredPresets.first?.id
        }

        return BrushLibraryState(
            presets: filteredPresets,
            selectedPresetID: resolvedSelectedPresetID
        )
    }

    func removingLikelyAutoSavedDuplicatePresets() -> BrushLibraryState {
        var filteredPresets: [BrushPreset] = []
        var resolvedSelectedPresetID = selectedPresetID

        for preset in presets {
            if preset.isLikelyAutoSavedDuplicateCandidate,
               let existing = filteredPresets.first(where: {
                   $0.isLikelyAutoSavedDuplicateCandidate && $0.brush == preset.brush
               }) {
                if resolvedSelectedPresetID == preset.id {
                    resolvedSelectedPresetID = existing.id
                }
                continue
            }
            filteredPresets.append(preset)
        }

        if let selectedPresetID = resolvedSelectedPresetID,
           filteredPresets.contains(where: { $0.id == selectedPresetID }) == false {
            resolvedSelectedPresetID = filteredPresets.first?.id
        }

        return BrushLibraryState(
            presets: filteredPresets,
            selectedPresetID: resolvedSelectedPresetID
        )
    }
}

struct BrushLibraryArchive: Codable, Sendable, Equatable {
    var version: Int = 3
    var library: BrushLibraryState
    var tipImageLibrary: TipImageLibraryState
    var tipImageAssets: [BrushTipImageAsset]

    init(
        version: Int = 3,
        library: BrushLibraryState,
        tipImageLibrary: TipImageLibraryState = .empty,
        tipImageAssets: [BrushTipImageAsset]? = nil
    ) {
        self.version = version
        if let tipImageAssets {
            self.library = library
            self.tipImageLibrary = tipImageLibrary
            self.tipImageAssets = tipImageAssets
        } else {
            let normalized = BrushTipImageAssetSystem.archivedLibrary(
                library,
                tipImageLibrary: tipImageLibrary
            )
            self.library = normalized.library
            self.tipImageLibrary = normalized.tipImageLibrary
            self.tipImageAssets = normalized.assets
        }
    }

    enum CodingKeys: String, CodingKey {
        case version
        case library
        case tipImageLibrary
        case tipImageAssets
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        version = try container.decodeIfPresent(Int.self, forKey: .version) ?? 1
        library = try container.decode(BrushLibraryState.self, forKey: .library)
        tipImageLibrary = try container.decodeIfPresent(TipImageLibraryState.self, forKey: .tipImageLibrary) ?? .empty
        tipImageAssets = try container.decodeIfPresent([BrushTipImageAsset].self, forKey: .tipImageAssets) ?? []
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(version, forKey: .version)
        try container.encode(library, forKey: .library)
        try container.encode(tipImageLibrary, forKey: .tipImageLibrary)
        try container.encode(tipImageAssets, forKey: .tipImageAssets)
    }

    var resolvedLibrary: BrushLibraryState {
        BrushTipImageAssetSystem.resolveLibrary(library, assets: tipImageAssets)
    }

    var resolvedTipImageLibrary: TipImageLibraryState {
        BrushTipImageAssetSystem.resolveTipImageLibrary(tipImageLibrary, assets: tipImageAssets)
    }
}
