import Foundation

struct BlockRay: Sendable, Equatable {
    var origin: BlockVector3
    var direction: BlockVector3
}

struct BlockMeshFace: Identifiable, Sendable, Equatable {
    var id: String { "\(objectID.uuidString)-\(faceIndex)" }
    var objectID: UUID
    var faceIndex: Int
    var vertices: [BlockVector3]
    var normal: BlockVector3
}

private struct BlockReferenceQuantizedEdge: Hashable {
    struct Point: Hashable, Comparable {
        var x: Int64
        var y: Int64
        var z: Int64

        static func < (lhs: Point, rhs: Point) -> Bool {
            if lhs.x != rhs.x { return lhs.x < rhs.x }
            if lhs.y != rhs.y { return lhs.y < rhs.y }
            return lhs.z < rhs.z
        }
    }

    var start: Point
    var end: Point
}

/// Marks silhouette/boundary/crease edges and suppresses coplanar subdivision
/// edges generated by CSG triangulation or polygon splitting.
func blockReferenceFeatureEdgeMask(
    faces: [BlockMeshFace],
    creaseDegrees: Double = 2
) -> [Int: [Bool]] {
    struct Use {
        var faceIndex: Int
        var edgeIndex: Int
        var normal: BlockVector3
    }
    func point(_ value: BlockVector3) -> BlockReferenceQuantizedEdge.Point {
        let scale = 100_000.0
        return .init(
            x: Int64((value.x * scale).rounded()),
            y: Int64((value.y * scale).rounded()),
            z: Int64((value.z * scale).rounded())
        )
    }
    var uses: [BlockReferenceQuantizedEdge: [Use]] = [:]
    var result = Dictionary(uniqueKeysWithValues: faces.map {
        ($0.faceIndex, Array(repeating: true, count: $0.vertices.count))
    })
    for face in faces where face.vertices.count >= 2 {
        for edgeIndex in face.vertices.indices {
            let a = point(face.vertices[edgeIndex])
            let b = point(face.vertices[(edgeIndex + 1) % face.vertices.count])
            let key = a < b
                ? BlockReferenceQuantizedEdge(start: a, end: b)
                : BlockReferenceQuantizedEdge(start: b, end: a)
            uses[key, default: []].append(.init(
                faceIndex: face.faceIndex,
                edgeIndex: edgeIndex,
                normal: face.normal.normalized(fallback: .unitZ)
            ))
        }
    }
    let threshold = cos(max(creaseDegrees, 0) * .pi / 180)
    for edgeUses in uses.values where edgeUses.count > 1 {
        let isCrease = edgeUses.enumerated().contains { index, use in
            edgeUses.dropFirst(index + 1).contains { use.normal.dot($0.normal) < threshold }
        }
        if !isCrease {
            for use in edgeUses {
                result[use.faceIndex]?[use.edgeIndex] = false
            }
        }
    }
    return result
}

struct BlockProjectedPoint: Sendable, Equatable {
    var canvasPoint: CanvasPoint
    var cameraDepth: Double
}

struct BlockCameraBasis: Sendable, Equatable {
    var position: BlockVector3
    var right: BlockVector3
    var up: BlockVector3
    var forward: BlockVector3
}

func blockCameraBasis(_ camera: BlockReferenceCamera) -> BlockCameraBasis {
    let yaw = camera.yawDegrees * .pi / 180
    let pitch = camera.pitchDegrees * .pi / 180
    let fromTarget = BlockVector3(
        x: cos(pitch) * cos(yaw),
        y: cos(pitch) * sin(yaw),
        z: sin(pitch)
    ).normalized(fallback: BlockVector3(x: 1, y: -1, z: 0.6).normalized())
    let position = camera.target + fromTarget * camera.distance
    let forward = (camera.target - position).normalized(fallback: BlockVector3(x: -1, y: 1, z: -0.6).normalized())
    // Derive the turntable horizontal axis from yaw, including at the poles.
    // Switching the reference up axis near a top view caused a visible 90° jump.
    var right = BlockVector3(x: -sin(yaw), y: cos(yaw), z: 0)
    var up = right.cross(forward).normalized(fallback: .unitZ)
    let roll = camera.rollDegrees * .pi / 180
    if abs(roll) > 0.000_000_1 {
        let baseRight = right
        let baseUp = up
        right = (baseRight * cos(roll) + baseUp * sin(roll)).normalized(fallback: baseRight)
        up = (baseUp * cos(roll) - baseRight * sin(roll)).normalized(fallback: baseUp)
    }
    return BlockCameraBasis(position: position, right: right, up: up, forward: forward)
}

func projectBlockPoint(
    _ point: BlockVector3,
    camera: BlockReferenceCamera,
    canvasSize: CanvasSize
) -> BlockProjectedPoint? {
    let basis = blockCameraBasis(camera)
    let relative = point - basis.position
    let depth = relative.dot(basis.forward)
    guard depth > 0.01 else { return nil }
    let width = Double(max(canvasSize.width, 1))
    let height = Double(max(canvasSize.height, 1))
    let aspect = width / height
    let fovScale = tan(camera.fieldOfViewDegrees * .pi / 360)
    let ndcX: Double
    let ndcY: Double
    if camera.isOrthographic {
        let verticalSpan = max(camera.distance * fovScale, 1)
        ndcX = relative.dot(basis.right) / (verticalSpan * aspect)
        ndcY = relative.dot(basis.up) / verticalSpan
    } else {
        ndcX = relative.dot(basis.right) / (depth * fovScale * aspect)
        ndcY = relative.dot(basis.up) / (depth * fovScale)
    }
    return BlockProjectedPoint(
        canvasPoint: CanvasPoint(
            x: (camera.principalPointNormalized.x + ndcX * 0.5) * width,
            y: (camera.principalPointNormalized.y - ndcY * 0.5) * height
        ),
        cameraDepth: depth
    )
}

func blockCameraRay(
    canvasPoint: CanvasPoint,
    camera: BlockReferenceCamera,
    canvasSize: CanvasSize
) -> BlockRay {
    let basis = blockCameraBasis(camera)
    let width = Double(max(canvasSize.width, 1))
    let height = Double(max(canvasSize.height, 1))
    let aspect = width / height
    let ndcX = ((canvasPoint.x / width) - camera.principalPointNormalized.x) * 2
    let ndcY = (camera.principalPointNormalized.y - (canvasPoint.y / height)) * 2
    let fovScale = tan(camera.fieldOfViewDegrees * .pi / 360)
    if camera.isOrthographic {
        let verticalSpan = max(camera.distance * fovScale, 1)
        let origin = basis.position
            + basis.right * (ndcX * verticalSpan * aspect)
            + basis.up * (ndcY * verticalSpan)
        return BlockRay(origin: origin, direction: basis.forward)
    }
    let direction = (
        basis.forward
        + basis.right * (ndcX * fovScale * aspect)
        + basis.up * (ndcY * fovScale)
    ).normalized(fallback: basis.forward)
    return BlockRay(origin: basis.position, direction: direction)
}

func intersectBlockRay(_ ray: BlockRay, with plane: BlockWorkingPlane) -> BlockVector3? {
    let denominator = ray.direction.dot(plane.normal)
    guard abs(denominator) > 0.000_001 else { return nil }
    let distance = (plane.origin - ray.origin).dot(plane.normal) / denominator
    guard distance.isFinite else { return nil }
    return ray.origin + ray.direction * distance
}

struct BlockReferenceGizmoMoveLayout: Sendable, Equatable {
    var axis: BlockReferenceAxis
    var start: CanvasPoint
    var end: CanvasPoint
    var canvasDirection: CanvasPoint
    var worldUnitsPerCanvasPixel: Double
}

struct BlockReferenceGizmoRingLayout: Sendable, Equatable {
    var axis: BlockReferenceAxis
    var points: [CanvasPoint]
}

struct BlockReferenceGizmoLayout: Sendable, Equatable {
    var center: CanvasPoint
    var moveHandles: [BlockReferenceGizmoMoveLayout]
    var scaleHandles: [BlockReferenceGizmoMoveLayout]
    var rotationRings: [BlockReferenceGizmoRingLayout]
}

func blockReferenceGizmoLayout(
    object: BlockReferenceObject,
    camera: BlockReferenceCamera,
    canvasSize: CanvasSize,
    screenScale: Double
) -> BlockReferenceGizmoLayout? {
    blockReferenceGizmoLayout(
        center: object.position,
        axisDirections: Dictionary(
            uniqueKeysWithValues: BlockReferenceAxis.allCases.map { ($0, $0.unitVector) }
        ),
        camera: camera,
        canvasSize: canvasSize,
        screenScale: screenScale
    )
}

func blockReferenceGizmoLayout(
    center worldCenter: BlockVector3,
    axisDirections: [BlockReferenceAxis: BlockVector3],
    camera: BlockReferenceCamera,
    canvasSize: CanvasSize,
    screenScale: Double
) -> BlockReferenceGizmoLayout? {
    guard let projectedCenter = projectBlockPoint(
        worldCenter,
        camera: camera,
        canvasSize: canvasSize
    ) else { return nil }
    let center = projectedCenter.canvasPoint
    let resolvedScale = max(screenScale, 0.000_001)
    let arrowStartDistance = 16 / resolvedScale
    let arrowEndDistance = 82 / resolvedScale
    let scaleStartDistance = 88 / resolvedScale
    let scaleEndDistance = 104 / resolvedScale
    let desiredRingRadius = 52 / resolvedScale

    var moveHandles: [BlockReferenceGizmoMoveLayout] = []
    var scaleHandles: [BlockReferenceGizmoMoveLayout] = []
    var rotationRings: [BlockReferenceGizmoRingLayout] = []

    for axis in BlockReferenceAxis.allCases {
        let worldAxis = axisDirections[axis]?.normalized(fallback: axis.unitVector) ?? axis.unitVector
        guard let projectedAxis = projectBlockPoint(
            worldCenter + worldAxis,
            camera: camera,
            canvasSize: canvasSize
        ) else { continue }
        let deltaX = projectedAxis.canvasPoint.x - center.x
        let deltaY = projectedAxis.canvasPoint.y - center.y
        let pixelsPerWorldUnit = hypot(deltaX, deltaY)
        if pixelsPerWorldUnit > 0.000_001 {
            let direction = CanvasPoint(
                x: deltaX / pixelsPerWorldUnit,
                y: deltaY / pixelsPerWorldUnit
            )
            moveHandles.append(BlockReferenceGizmoMoveLayout(
                axis: axis,
                start: CanvasPoint(
                    x: center.x + direction.x * arrowStartDistance,
                    y: center.y + direction.y * arrowStartDistance
                ),
                end: CanvasPoint(
                    x: center.x + direction.x * arrowEndDistance,
                    y: center.y + direction.y * arrowEndDistance
                ),
                canvasDirection: direction,
                worldUnitsPerCanvasPixel: 1 / pixelsPerWorldUnit
            ))
            scaleHandles.append(BlockReferenceGizmoMoveLayout(
                axis: axis,
                start: CanvasPoint(
                    x: center.x + direction.x * scaleStartDistance,
                    y: center.y + direction.y * scaleStartDistance
                ),
                end: CanvasPoint(
                    x: center.x + direction.x * scaleEndDistance,
                    y: center.y + direction.y * scaleEndDistance
                ),
                canvasDirection: direction,
                worldUnitsPerCanvasPixel: 1 / pixelsPerWorldUnit
            ))
        }

        let ringBasis = blockReferenceGizmoRingBasis(worldAxis)
        let projectedBasisLengths = [ringBasis.u, ringBasis.v].compactMap { basis -> Double? in
            guard let projected = projectBlockPoint(
                worldCenter + basis,
                camera: camera,
                canvasSize: canvasSize
            ) else { return nil }
            return hypot(
                projected.canvasPoint.x - center.x,
                projected.canvasPoint.y - center.y
            )
        }
        guard let largestBasisLength = projectedBasisLengths.max(),
              largestBasisLength > 0.000_001 else { continue }
        let worldRadius = min(
            max(desiredRingRadius / largestBasisLength, 1),
            max(camera.distance * 0.35, 1)
        )
        let segmentCount = 48
        let points = (0...segmentCount).compactMap { index -> CanvasPoint? in
            let angle = Double(index) / Double(segmentCount) * 2 * .pi
            let worldPoint = worldCenter
                + ringBasis.u * (cos(angle) * worldRadius)
                + ringBasis.v * (sin(angle) * worldRadius)
            return projectBlockPoint(
                worldPoint,
                camera: camera,
                canvasSize: canvasSize
            )?.canvasPoint
        }
        if points.count == segmentCount + 1 {
            rotationRings.append(BlockReferenceGizmoRingLayout(axis: axis, points: points))
        }
    }
    return BlockReferenceGizmoLayout(
        center: center,
        moveHandles: moveHandles,
        scaleHandles: scaleHandles,
        rotationRings: rotationRings
    )
}

func blockReferenceGizmoHitTest(
    point: CanvasPoint,
    layout: BlockReferenceGizmoLayout,
    screenScale: Double
) -> BlockReferenceGizmoHandle? {
    let tolerance = 9 / max(screenScale, 0.000_001)
    let arrowHeadTolerance = 12 / max(screenScale, 0.000_001)

    if blockCanvasDistance(point, layout.center) <= arrowHeadTolerance {
        return BlockReferenceGizmoHandle(kind: .scale, axis: .x, isUniformScale: true)
    }

    if let endpoint = layout.scaleHandles.min(by: {
        blockCanvasDistance(point, $0.end) < blockCanvasDistance(point, $1.end)
    }), blockCanvasDistance(point, endpoint.end) <= arrowHeadTolerance {
        return BlockReferenceGizmoHandle(kind: .scale, axis: endpoint.axis)
    }

    if let endpoint = layout.moveHandles.min(by: {
        blockCanvasDistance(point, $0.end) < blockCanvasDistance(point, $1.end)
    }), blockCanvasDistance(point, endpoint.end) <= arrowHeadTolerance {
        return BlockReferenceGizmoHandle(kind: .move, axis: endpoint.axis)
    }

    var closestRing: (axis: BlockReferenceAxis, distance: Double)?
    for ring in layout.rotationRings {
        for index in 1..<ring.points.count {
            let distance = blockCanvasPointToSegmentDistance(
                point,
                start: ring.points[index - 1],
                end: ring.points[index]
            )
            if closestRing == nil || distance < closestRing!.distance {
                closestRing = (ring.axis, distance)
            }
        }
    }
    if let closestRing, closestRing.distance <= tolerance {
        return BlockReferenceGizmoHandle(kind: .rotate, axis: closestRing.axis)
    }

    if let shaft = layout.moveHandles.min(by: {
        blockCanvasPointToSegmentDistance(point, start: $0.start, end: $0.end)
            < blockCanvasPointToSegmentDistance(point, start: $1.start, end: $1.end)
    }), blockCanvasPointToSegmentDistance(
        point,
        start: shaft.start,
        end: shaft.end
    ) <= tolerance {
        return BlockReferenceGizmoHandle(kind: .move, axis: shaft.axis)
    }
    return nil
}

func blockReferenceGizmoRotationPlane(
    center: BlockVector3,
    axis: BlockReferenceAxis
) -> BlockWorkingPlane {
    blockReferenceGizmoRotationPlane(center: center, axisVector: axis.unitVector)
}

func blockReferenceGizmoRotationPlane(
    center: BlockVector3,
    axisVector: BlockVector3
) -> BlockWorkingPlane {
    let normal = axisVector.normalized(fallback: .unitZ)
    let basis = blockReferenceGizmoRingBasis(normal)
    return BlockWorkingPlane(
        origin: center,
        axisU: basis.u,
        axisV: basis.v,
        normal: normal
    )
}

func blockReferenceGizmoSignedAngleDegrees(
    from start: BlockVector3,
    to end: BlockVector3,
    around axis: BlockReferenceAxis
) -> Double {
    blockReferenceGizmoSignedAngleDegrees(
        from: start,
        to: end,
        around: axis.unitVector
    )
}

func blockReferenceGizmoSignedAngleDegrees(
    from start: BlockVector3,
    to end: BlockVector3,
    around axisVector: BlockVector3
) -> Double {
    let startVector = start.normalized()
    let endVector = end.normalized()
    let axis = axisVector.normalized(fallback: .unitZ)
    let sine = axis.dot(startVector.cross(endVector))
    let cosine = min(max(startVector.dot(endVector), -1), 1)
    return atan2(sine, cosine) * 180 / .pi
}

private func blockReferenceGizmoRingBasis(
    _ axis: BlockReferenceAxis
) -> (u: BlockVector3, v: BlockVector3) {
    blockReferenceGizmoRingBasis(axis.unitVector)
}

private func blockReferenceGizmoRingBasis(
    _ axisVector: BlockVector3
) -> (u: BlockVector3, v: BlockVector3) {
    let axis = axisVector.normalized(fallback: .unitZ)
    let reference: BlockVector3 = abs(axis.z) < 0.85 ? .unitZ : .unitY
    let u = reference.cross(axis).normalized(fallback: .unitX)
    let v = axis.cross(u).normalized(fallback: .unitY)
    return (u, v)
}

private func blockCanvasDistance(_ lhs: CanvasPoint, _ rhs: CanvasPoint) -> Double {
    hypot(lhs.x - rhs.x, lhs.y - rhs.y)
}

private func blockCanvasPointToSegmentDistance(
    _ point: CanvasPoint,
    start: CanvasPoint,
    end: CanvasPoint
) -> Double {
    let deltaX = end.x - start.x
    let deltaY = end.y - start.y
    let lengthSquared = deltaX * deltaX + deltaY * deltaY
    guard lengthSquared > 0.000_001 else { return blockCanvasDistance(point, start) }
    let projection = ((point.x - start.x) * deltaX + (point.y - start.y) * deltaY) / lengthSquared
    let clamped = min(max(projection, 0), 1)
    return blockCanvasDistance(
        point,
        CanvasPoint(x: start.x + deltaX * clamped, y: start.y + deltaY * clamped)
    )
}

func blockObjectFaces(_ object: BlockReferenceObject, radialSegments requestedSegments: Int? = nil) -> [BlockMeshFace] {
    let radialSegments = min(max(requestedSegments ?? object.radialSegments, 8), 32)
    let localFaces: [[BlockVector3]]
    if let customMesh = object.customMesh {
        let base = customMesh.baseDimensions
        let scale = BlockVector3(
            x: object.dimensions.width / base.width,
            y: object.dimensions.depth / base.depth,
            z: object.dimensions.height / base.height
        )
        localFaces = customMesh.faces.map { face in
            face.map { point in
                BlockVector3(
                    x: point.x * scale.x,
                    y: point.y * scale.y,
                    z: point.z * scale.z
                )
            }
        }
    } else {
        switch object.kind {
        case .box:
            localFaces = blockBoxFaces(dimensions: object.dimensions)
        case .cylinder:
            localFaces = blockCylinderFaces(dimensions: object.dimensions, radialSegments: radialSegments, topScale: 1)
        case .cone:
            localFaces = blockCylinderFaces(dimensions: object.dimensions, radialSegments: radialSegments, topScale: 0)
        case .sphere:
            localFaces = blockSphereFaces(dimensions: object.dimensions, radialSegments: radialSegments)
        }
    }
    return localFaces.enumerated().compactMap { index, localVertices in
        let worldVertices = localVertices.map { blockTransformPoint($0, object: object) }
        guard worldVertices.count >= 3 else { return nil }
        let normal = (worldVertices[1] - worldVertices[0])
            .cross(worldVertices[2] - worldVertices[0])
            .normalized()
        return BlockMeshFace(
            objectID: object.id,
            faceIndex: index,
            vertices: worldVertices,
            normal: normal
        )
    }
}

/// Produces a real geometric reflection. Mirroring only an object's origin and
/// Euler angles cannot represent a reflection because a reflection has a
/// negative determinant and is not a rotation.
func blockReferenceMirroredObject(
    _ source: BlockReferenceObject,
    pivot: BlockVector3,
    normal rawNormal: BlockVector3,
    name: String
) -> BlockReferenceObject? {
    let normal = rawNormal.normalized(fallback: .unitX)
    let reflectedFaces = blockObjectFaces(source).map { face in
        face.vertices.reversed().map { point in
            point - normal * (2 * (point - pivot).dot(normal))
        }
    }
    let vertices = reflectedFaces.flatMap { $0 }
    guard let first = vertices.first else { return nil }
    var minimum = first
    var maximum = first
    for point in vertices.dropFirst() {
        minimum.x = min(minimum.x, point.x)
        minimum.y = min(minimum.y, point.y)
        minimum.z = min(minimum.z, point.z)
        maximum.x = max(maximum.x, point.x)
        maximum.y = max(maximum.y, point.y)
        maximum.z = max(maximum.z, point.z)
    }
    let center = (minimum + maximum) * 0.5
    var dimensions = BlockDimensions(
        width: maximum.x - minimum.x,
        depth: maximum.y - minimum.y,
        height: maximum.z - minimum.z
    )
    dimensions.normalize()
    return BlockReferenceObject(
        name: name,
        kind: source.kind,
        position: center,
        dimensions: dimensions,
        customMesh: BlockReferenceCustomMesh(
            faces: reflectedFaces.map { $0.map { $0 - center } },
            baseDimensions: dimensions
        ),
        style: source.style
    )
}

func blockTransformPoint(_ point: BlockVector3, object: BlockReferenceObject) -> BlockVector3 {
    object.position + blockRotate(point, rotation: object.rotation)
}

func blockInverseTransformPoint(_ point: BlockVector3, object: BlockReferenceObject) -> BlockVector3 {
    let relative = point - object.position
    let axisX = blockRotate(.unitX, rotation: object.rotation)
    let axisY = blockRotate(.unitY, rotation: object.rotation)
    let axisZ = blockRotate(.unitZ, rotation: object.rotation)
    return BlockVector3(
        x: relative.dot(axisX),
        y: relative.dot(axisY),
        z: relative.dot(axisZ)
    )
}

func blockReferenceObjectModuleBasePoint(_ object: BlockReferenceObject) -> BlockVector3? {
    guard object.moduleKind != nil else { return nil }
    return blockTransformPoint(object.moduleBasePointOffset ?? .zero, object: object)
}

func blockRotate(_ point: BlockVector3, rotation: BlockEulerRotation) -> BlockVector3 {
    let x = rotation.xDegrees * .pi / 180
    let y = rotation.yDegrees * .pi / 180
    let z = rotation.zDegrees * .pi / 180
    let xRotated = BlockVector3(
        x: point.x,
        y: point.y * cos(x) - point.z * sin(x),
        z: point.y * sin(x) + point.z * cos(x)
    )
    let yRotated = BlockVector3(
        x: xRotated.x * cos(y) + xRotated.z * sin(y),
        y: xRotated.y,
        z: -xRotated.x * sin(y) + xRotated.z * cos(y)
    )
    return BlockVector3(
        x: yRotated.x * cos(z) - yRotated.y * sin(z),
        y: yRotated.x * sin(z) + yRotated.y * cos(z),
        z: yRotated.z
    )
}

func blockRotateAroundAxis(
    _ point: BlockVector3,
    axis: BlockVector3,
    degrees: Double
) -> BlockVector3 {
    let unitAxis = axis.normalized(fallback: .unitZ)
    let radians = degrees * .pi / 180
    let cosine = cos(radians)
    let sine = sin(radians)
    return point * cosine
        + unitAxis.cross(point) * sine
        + unitAxis * (unitAxis.dot(point) * (1 - cosine))
}

func blockRotation(
    applyingWorldAxis axis: BlockReferenceAxis,
    degrees: Double,
    to rotation: BlockEulerRotation
) -> BlockEulerRotation {
    blockRotation(
        applyingWorldAxisVector: axis.unitVector,
        degrees: degrees,
        to: rotation
    )
}

func blockRotation(
    applyingWorldAxisVector axisVector: BlockVector3,
    degrees: Double,
    to rotation: BlockEulerRotation
) -> BlockEulerRotation {
    let axisX = blockRotateAroundAxis(
        blockRotate(.unitX, rotation: rotation),
        axis: axisVector,
        degrees: degrees
    )
    let axisY = blockRotateAroundAxis(
        blockRotate(.unitY, rotation: rotation),
        axis: axisVector,
        degrees: degrees
    )
    let axisZ = blockRotateAroundAxis(
        blockRotate(.unitZ, rotation: rotation),
        axis: axisVector,
        degrees: degrees
    )
    return blockEulerRotation(axisX: axisX, axisY: axisY, axisZ: axisZ)
}

func blockApplyRotationBasisChange(
    _ vector: BlockVector3,
    from source: BlockEulerRotation,
    to target: BlockEulerRotation
) -> BlockVector3 {
    let sourceX = blockRotate(.unitX, rotation: source)
    let sourceY = blockRotate(.unitY, rotation: source)
    let sourceZ = blockRotate(.unitZ, rotation: source)
    let targetX = blockRotate(.unitX, rotation: target)
    let targetY = blockRotate(.unitY, rotation: target)
    let targetZ = blockRotate(.unitZ, rotation: target)
    return targetX * vector.dot(sourceX)
        + targetY * vector.dot(sourceY)
        + targetZ * vector.dot(sourceZ)
}

func blockRotation(
    applyingBasisChangeFrom source: BlockEulerRotation,
    to target: BlockEulerRotation,
    to rotation: BlockEulerRotation
) -> BlockEulerRotation {
    blockEulerRotation(
        axisX: blockApplyRotationBasisChange(
            blockRotate(.unitX, rotation: rotation),
            from: source,
            to: target
        ),
        axisY: blockApplyRotationBasisChange(
            blockRotate(.unitY, rotation: rotation),
            from: source,
            to: target
        ),
        axisZ: blockApplyRotationBasisChange(
            blockRotate(.unitZ, rotation: rotation),
            from: source,
            to: target
        )
    )
}

private func blockEulerRotation(
    axisX: BlockVector3,
    axisY: BlockVector3,
    axisZ: BlockVector3
) -> BlockEulerRotation {
    let m00 = axisX.x
    let m10 = axisX.y
    let m20 = axisX.z
    let m11 = axisY.y
    let m12 = axisZ.y
    let m21 = axisY.z
    let m22 = axisZ.z
    let sineY = min(max(-m20, -1), 1)
    let x: Double
    let y = asin(sineY)
    let z: Double
    if abs(sineY) < 0.999_999 {
        x = atan2(m21, m22)
        z = atan2(m10, m00)
    } else {
        x = atan2(-m12, m11)
        z = 0
    }
    var result = BlockEulerRotation(
        xDegrees: x * 180 / .pi,
        yDegrees: y * 180 / .pi,
        zDegrees: z * 180 / .pi
    )
    result.normalize()
    return result
}

func blockObjectSnapPoints(_ object: BlockReferenceObject) -> [(kind: BlockReferenceSnapKind, point: BlockVector3)] {
    let faces = blockObjectFaces(object)
    var result: [(BlockReferenceSnapKind, BlockVector3)] = [(.center, object.position)]
    var seen = Set<BlockVector3>()
    for face in faces {
        if !face.vertices.isEmpty {
            result.append((
                .faceCenter,
                face.vertices.reduce(.zero, +) / Double(face.vertices.count)
            ))
        }
        for vertex in face.vertices where seen.insert(vertex).inserted {
            result.append((.vertex, vertex))
        }
        guard face.vertices.count >= 2 else { continue }
        for index in face.vertices.indices {
            let next = face.vertices[(index + 1) % face.vertices.count]
            result.append((.midpoint, (face.vertices[index] + next) * 0.5))
        }
    }
    return result
}

func snappedBlockPoint(
    _ point: BlockVector3,
    scene: BlockReferenceScene,
    canvasSize: CanvasSize,
    screenScale: Double
) -> (point: BlockVector3, kind: BlockReferenceSnapKind?) {
    let plane = scene.workingPlane
    let coordinates = plane.coordinates(of: point)
    let toleranceCanvasPixels = scene.snap.screenTolerancePoints / max(screenScale, 0.000_001)
    var bestPoint = point
    var bestKind: BlockReferenceSnapKind?
    var bestScreenDistance = Double.greatestFiniteMagnitude

    if scene.snap.enabledKinds.contains(.grid) {
        let spacing = max(scene.snap.gridSpacing, 1)
        let candidate = plane.worldPoint(
            u: (coordinates.u / spacing).rounded() * spacing,
            v: (coordinates.v / spacing).rounded() * spacing,
            height: coordinates.height
        )
        if let originalProjected = projectBlockPoint(point, camera: scene.camera, canvasSize: canvasSize),
           let candidateProjected = projectBlockPoint(candidate, camera: scene.camera, canvasSize: canvasSize) {
            let distance = hypot(
                originalProjected.canvasPoint.x - candidateProjected.canvasPoint.x,
                originalProjected.canvasPoint.y - candidateProjected.canvasPoint.y
            )
            if distance <= toleranceCanvasPixels {
                bestPoint = candidate
                bestKind = .grid
                bestScreenDistance = distance
            }
        }
    }

    guard let originalProjected = projectBlockPoint(point, camera: scene.camera, canvasSize: canvasSize) else {
        return (bestPoint, bestKind)
    }
    for object in scene.objects where object.isVisible && object.style.participatesInSnapping {
        for candidate in blockObjectSnapPoints(object)
        where scene.snap.enabledKinds.contains(candidate.kind) {
            let planeDistance = abs(plane.coordinates(of: candidate.point).height)
            guard planeDistance <= max(scene.snap.gridSpacing * 0.05, 0.5),
                  let projected = projectBlockPoint(candidate.point, camera: scene.camera, canvasSize: canvasSize) else { continue }
            let screenDistance = hypot(
                originalProjected.canvasPoint.x - projected.canvasPoint.x,
                originalProjected.canvasPoint.y - projected.canvasPoint.y
            )
            if screenDistance <= toleranceCanvasPixels, screenDistance < bestScreenDistance {
                bestPoint = candidate.point
                bestKind = candidate.kind
                bestScreenDistance = screenDistance
            }
        }
    }
    return (bestPoint, bestKind)
}

struct BlockExtrusionSnapResult: Sendable, Equatable {
    var height: Double
    var snapPoint: BlockVector3?
    var kind: BlockReferenceSnapKind?
}

/// Snaps an extrusion along its construction-plane normal. Vertex candidates are
/// compared by their projected height along that normal, so the source vertex may
/// belong to another object without having to sit directly above the draft.
func snappedBlockExtrusionHeight(
    _ rawHeight: Double,
    draft: BlockCreationDraft,
    scene: BlockReferenceScene,
    canvasSize: CanvasSize,
    screenScale: Double
) -> BlockExtrusionSnapResult {
    let minimumHeight = 1.0
    let resolvedRawHeight = max(rawHeight, minimumHeight)
    let normal = draft.plane.normal.normalized()
    let center = draft.center
    let toleranceCanvasPixels = scene.snap.screenTolerancePoints / max(screenScale, 0.000_001)

    if scene.snap.enabledKinds.contains(.vertex),
       let rawTop = projectBlockPoint(
           center + normal * resolvedRawHeight,
           camera: scene.camera,
           canvasSize: canvasSize
       ) {
        var best: (height: Double, point: BlockVector3, distance: Double)?
        for object in scene.objects where object.isVisible {
            for candidate in blockObjectSnapPoints(object) where candidate.kind == .vertex {
                let candidateHeight = (candidate.point - center).dot(normal)
                guard candidateHeight >= minimumHeight,
                      let projectedTop = projectBlockPoint(
                          center + normal * candidateHeight,
                          camera: scene.camera,
                          canvasSize: canvasSize
                      ) else { continue }
                let distance = hypot(
                    rawTop.canvasPoint.x - projectedTop.canvasPoint.x,
                    rawTop.canvasPoint.y - projectedTop.canvasPoint.y
                )
                if distance <= toleranceCanvasPixels,
                   distance < (best?.distance ?? .greatestFiniteMagnitude) {
                    best = (candidateHeight, candidate.point, distance)
                }
            }
        }
        if let best {
            return BlockExtrusionSnapResult(
                height: best.height,
                snapPoint: best.point,
                kind: .vertex
            )
        }
    }

    if scene.snap.enabledKinds.contains(.grid) {
        let spacing = max(scene.snap.gridSpacing, 1)
        return BlockExtrusionSnapResult(
            height: max((rawHeight / spacing).rounded() * spacing, minimumHeight),
            snapPoint: nil,
            kind: .grid
        )
    }
    return BlockExtrusionSnapResult(
        height: resolvedRawHeight,
        snapPoint: nil,
        kind: nil
    )
}

func blockHitTestFace(
    scene: BlockReferenceScene,
    canvasPoint: CanvasPoint,
    canvasSize: CanvasSize
) -> BlockMeshFace? {
    var hit: (face: BlockMeshFace, depth: Double)?
    for object in scene.objects where object.isVisible && !object.isLocked {
        for face in blockObjectFaces(object) {
            let projected = face.vertices.compactMap {
                projectBlockPoint($0, camera: scene.camera, canvasSize: canvasSize)
            }
            guard projected.count == face.vertices.count,
                  blockPolygonContains(canvasPoint, polygon: projected.map(\.canvasPoint)) else { continue }
            let depth = projected.map(\.cameraDepth).reduce(0, +) / Double(projected.count)
            if hit == nil || depth < hit!.depth {
                hit = (face, depth)
            }
        }
    }
    return hit?.face
}

func blockWorkingPlane(from face: BlockMeshFace) -> BlockWorkingPlane? {
    guard face.vertices.count >= 3 else { return nil }
    let origin = face.vertices.reduce(.zero, +) / Double(face.vertices.count)
    let axisU = (face.vertices[1] - face.vertices[0]).normalized(fallback: .unitX)
    return BlockWorkingPlane(
        origin: origin,
        axisU: axisU,
        axisV: face.normal.cross(axisU),
        normal: face.normal,
        sourceObjectID: face.objectID,
        sourceFaceIndex: face.faceIndex
    )
}

func blockReferenceConstructionPlane(
    scene: BlockReferenceScene,
    canvasPoint: CanvasPoint,
    canvasSize: CanvasSize,
    buildsDirectlyOnSurfaces: Bool
) -> BlockWorkingPlane {
    guard buildsDirectlyOnSurfaces,
          let face = blockHitTestFace(
              scene: scene,
              canvasPoint: canvasPoint,
              canvasSize: canvasSize
          ),
          let plane = blockWorkingPlane(from: face) else {
        return scene.workingPlane
    }
    return plane
}

func blockReferenceScrubbedParameterValue(
    startValue: Double,
    horizontalTranslation: Double,
    sensitivity: Double,
    precisionScale: Double = 1,
    minimumValue: Double? = nil
) -> Double {
    guard startValue.isFinite,
          horizontalTranslation.isFinite,
          sensitivity.isFinite,
          precisionScale.isFinite else { return startValue }
    let rawValue = startValue + horizontalTranslation * sensitivity * precisionScale
    let roundedValue = (rawValue * 10).rounded() / 10
    guard let minimumValue, minimumValue.isFinite else { return roundedValue }
    return max(roundedValue, minimumValue)
}

func blockRotation(alignedTo plane: BlockWorkingPlane) -> BlockEulerRotation {
    let xAxis = plane.axisU
    let yAxis = plane.axisV
    let zAxis = plane.normal
    let yRadians = asin(min(max(-xAxis.z, -1), 1))
    let cosineY = cos(yRadians)
    let xRadians: Double
    let zRadians: Double
    if abs(cosineY) > 0.000_001 {
        xRadians = atan2(yAxis.z, zAxis.z)
        zRadians = atan2(xAxis.y, xAxis.x)
    } else {
        xRadians = atan2(-zAxis.y, yAxis.y)
        zRadians = 0
    }
    return BlockEulerRotation(
        xDegrees: xRadians * 180 / .pi,
        yDegrees: yRadians * 180 / .pi,
        zDegrees: zRadians * 180 / .pi
    )
}

func blockPolygonContains(_ point: CanvasPoint, polygon: [CanvasPoint]) -> Bool {
    guard polygon.count >= 3 else { return false }
    var isInside = false
    var previous = polygon[polygon.count - 1]
    for current in polygon {
        let denominator = previous.y - current.y
        let intersectionX = abs(denominator) > 0.000_000_1
            ? ((previous.x - current.x) * (point.y - current.y) / denominator) + current.x
            : current.x
        let crosses = ((current.y > point.y) != (previous.y > point.y)) && point.x < intersectionX
        if crosses { isInside.toggle() }
        previous = current
    }
    return isInside
}

func blockBoxFaces(dimensions: BlockDimensions) -> [[BlockVector3]] {
    let x = dimensions.width * 0.5
    let y = dimensions.depth * 0.5
    let z = dimensions.height
    let v = [
        BlockVector3(x: -x, y: -y, z: 0), BlockVector3(x: x, y: -y, z: 0),
        BlockVector3(x: x, y: y, z: 0), BlockVector3(x: -x, y: y, z: 0),
        BlockVector3(x: -x, y: -y, z: z), BlockVector3(x: x, y: -y, z: z),
        BlockVector3(x: x, y: y, z: z), BlockVector3(x: -x, y: y, z: z)
    ]
    return [
        [v[0], v[3], v[2], v[1]], [v[4], v[5], v[6], v[7]],
        [v[0], v[1], v[5], v[4]], [v[1], v[2], v[6], v[5]],
        [v[2], v[3], v[7], v[6]], [v[3], v[0], v[4], v[7]]
    ]
}

func blockCylinderFaces(
    dimensions: BlockDimensions,
    radialSegments: Int,
    topScale: Double
) -> [[BlockVector3]] {
    let segments = max(radialSegments, 8)
    let rx = dimensions.width * 0.5
    let ry = dimensions.depth * 0.5
    let bottom = (0..<segments).map { index -> BlockVector3 in
        let angle = Double(index) / Double(segments) * .pi * 2
        return BlockVector3(x: cos(angle) * rx, y: sin(angle) * ry, z: 0)
    }
    let top = bottom.map { BlockVector3(x: $0.x * topScale, y: $0.y * topScale, z: dimensions.height) }
    var faces: [[BlockVector3]] = [Array(bottom.reversed())]
    if topScale > 0.000_1 { faces.append(top) }
    for index in 0..<segments {
        let next = (index + 1) % segments
        if topScale > 0.000_1 {
            faces.append([bottom[index], bottom[next], top[next], top[index]])
        } else {
            faces.append([bottom[index], bottom[next], BlockVector3(x: 0, y: 0, z: dimensions.height)])
        }
    }
    return faces
}

func blockSphereFaces(dimensions: BlockDimensions, radialSegments: Int) -> [[BlockVector3]] {
    let longitudeCount = max(radialSegments, 6)
    let latitudeCount = max(longitudeCount / 2, 4)
    let rx = dimensions.width * 0.5
    let ry = dimensions.depth * 0.5
    let rz = dimensions.height * 0.5
    let centerZ = rz
    var rings: [[BlockVector3]] = []
    for latitude in 1..<latitudeCount {
        let phi = -.pi / 2 + Double(latitude) / Double(latitudeCount) * .pi
        rings.append((0..<longitudeCount).map { longitude in
            let theta = Double(longitude) / Double(longitudeCount) * .pi * 2
            return BlockVector3(
                x: cos(phi) * cos(theta) * rx,
                y: cos(phi) * sin(theta) * ry,
                z: centerZ + sin(phi) * rz
            )
        })
    }
    var faces: [[BlockVector3]] = []
    let bottomPole = BlockVector3(x: 0, y: 0, z: 0)
    let topPole = BlockVector3(x: 0, y: 0, z: dimensions.height)
    for longitude in 0..<longitudeCount {
        let next = (longitude + 1) % longitudeCount
        faces.append([bottomPole, rings[0][next], rings[0][longitude]])
    }
    for latitude in 0..<(rings.count - 1) {
        for longitude in 0..<longitudeCount {
            let next = (longitude + 1) % longitudeCount
            faces.append([
                rings[latitude][longitude], rings[latitude][next],
                rings[latitude + 1][next], rings[latitude + 1][longitude]
            ])
        }
    }
    let topRing = rings[rings.count - 1]
    for longitude in 0..<longitudeCount {
        let next = (longitude + 1) % longitudeCount
        faces.append([topRing[longitude], topRing[next], topPole])
    }
    return faces
}

func blockReferenceModuleObject(
    kind: BlockReferenceModuleKind,
    name: String,
    position: BlockVector3,
    rotation: BlockEulerRotation = .zero,
    parameters: BlockReferenceModuleParameters = .default,
    pose: BlockHumanPose = .standing
) -> BlockReferenceObject {
    let dimensions: BlockDimensions
    let faces: [[BlockVector3]]
    if let advanced = blockReferenceAdvancedModuleGeometry(
        kind: kind,
        parameters: parameters,
        pose: pose
    ) {
        return BlockReferenceObject(
            name: name,
            kind: .box,
            position: position,
            rotation: rotation,
            dimensions: advanced.dimensions,
            customMesh: BlockReferenceCustomMesh(
                faces: advanced.faces,
                baseDimensions: advanced.dimensions
            ),
            moduleKind: kind,
            moduleBasePointOffset: .zero,
            humanPose: kind == .poseableHuman ? pose : nil,
            moduleParameters: kind.isParametric ? parameters : nil
        )
    }
    switch kind {
    case .standingHuman:
        dimensions = BlockDimensions(width: 42, depth: 24, height: 170)
        faces = blockReferenceTranslatedFaces(
            blockBoxFaces(dimensions: .init(width: 24, depth: 20, height: 45)),
            by: .zero
        ) + blockReferenceTranslatedFaces(
            blockBoxFaces(dimensions: .init(width: 32, depth: 22, height: 45)),
            by: BlockVector3(x: 0, y: 0, z: 45)
        ) + blockReferenceTranslatedFaces(
            blockBoxFaces(dimensions: .init(width: 42, depth: 24, height: 56)),
            by: BlockVector3(x: 0, y: 0, z: 90)
        ) + blockReferenceTranslatedFaces(
            blockSphereFaces(
                dimensions: .init(width: 22, depth: 20, height: 24),
                radialSegments: 6
            ),
            by: BlockVector3(x: 0, y: 0, z: 146)
        )

    case .seatedHuman:
        dimensions = BlockDimensions(width: 42, depth: 74, height: 132)
        faces = blockReferenceTranslatedFaces(
            blockBoxFaces(dimensions: .init(width: 26, depth: 20, height: 43)),
            by: BlockVector3(x: 0, y: 52, z: 0)
        ) + blockReferenceTranslatedFaces(
            blockBoxFaces(dimensions: .init(width: 34, depth: 52, height: 20)),
            by: BlockVector3(x: 0, y: 26, z: 43)
        ) + blockReferenceTranslatedFaces(
            blockBoxFaces(dimensions: .init(width: 42, depth: 24, height: 50)),
            by: BlockVector3(x: 0, y: 0, z: 58)
        ) + blockReferenceTranslatedFaces(
            blockSphereFaces(
                dimensions: .init(width: 22, depth: 20, height: 24),
                radialSegments: 6
            ),
            by: BlockVector3(x: 0, y: 0, z: 108)
        )
    case .squareFrustum, .squarePyramid, .hemisphere, .torus, .hollowCylinder,
         .sedan, .suv, .smallTruck, .largeTruck, .bicycle, .motorcycle,
         .poseableHuman, .stairs, .doorFrame, .roomBox, .table:
        preconditionFailure("Advanced module geometry must resolve before the legacy switch")
    }

    return BlockReferenceObject(
        name: name,
        kind: .box,
        position: position,
        rotation: rotation,
        dimensions: dimensions,
        customMesh: BlockReferenceCustomMesh(
            faces: faces,
            baseDimensions: dimensions
        ),
        moduleKind: kind,
        moduleBasePointOffset: .zero
    )
}

func blockReferenceTranslatedFaces(
    _ faces: [[BlockVector3]],
    by offset: BlockVector3
) -> [[BlockVector3]] {
    faces.map { face in face.map { $0 + offset } }
}
